### ISSUE TITLE
Légende carte bruit

### ISSUE THREAD

**Issue by arnaudcan** [Ifsttar/NoiseMap#33]
Ce serait bien d'afficher la barre de couleurs quand on visualise une carte de bruit calculée sous noisemap.

**Comment by nicolas-f** [comment]
L'interface graphique est celle d'OrbisGIS. https://github.com/orbisgis/orbisgis/issues

La légende peut être visible lors de l'export via le plugin map composer. A l'heure actuelle ce plugin semble ne plus fonctionner.

**Comment by nicolas-f** [comment]
Le plugin fonctionne mais la légende n'est pas encore implémenté dans OrbisGIS. C'est bien ça @ebocher @SPalominos
